# Generated by Django 3.2.9 on 2022-01-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20220115_1133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='married',
            options={'ordering': ['person'], 'verbose_name': 'Married', 'verbose_name_plural': 'Married'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['surname', 'first_name'], 'verbose_name': 'Person', 'verbose_name_plural': 'People'},
        ),
        migrations.AlterModelOptions(
            name='personchildren',
            options={'ordering': ['person'], 'verbose_name': 'PersonChildren', 'verbose_name_plural': 'Persons Children'},
        ),
        migrations.AlterModelOptions(
            name='personparent',
            options={'ordering': ['person'], 'verbose_name': 'PersonParent', 'verbose_name_plural': 'Persons Parents'},
        ),
        migrations.AddField(
            model_name='person',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
