# Generated by Django 3.2.9 on 2022-01-17 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20220117_0824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='married',
            options={'ordering': ['person'], 'verbose_name_plural': 'Married'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['surname', 'first_name'], 'verbose_name_plural': 'People'},
        ),
        migrations.AlterModelOptions(
            name='personchildren',
            options={'ordering': ['person'], 'verbose_name_plural': 'Persons Children'},
        ),
        migrations.AlterModelOptions(
            name='personparent',
            options={'ordering': ['person'], 'verbose_name_plural': 'Persons Parents'},
        ),
    ]
