# Generated by Django 3.2.9 on 2022-01-18 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0005_person_init'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='complexion',
            field=models.CharField(blank=True, choices=[('Dark', 'Dark'), ('Fair', 'Fair')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
